### ISSUE TITLE
M5Tough.h:134:12: error: extended character “ is not valid

### ISSUE THREAD

**Issue by mgrouch** [m5stack/M5Tough#11]
/home/runner/Arduino/libraries/CustomLibrary_M5Tough/src/M5Tough.h:134:12: error: extended character “ is not valid in an identifier
  134 |     #error “This library only supports boards with ESP32 processor.”
      |            ^
/home/runner/Arduino/libraries/CustomLibrary_M5Tough/src/M5Tough.h:134:68: error: extended character ” is not valid in an identifier
  134 |     #error “This library only supports boards with ESP32 processor.”
      |                                                                    ^

**Comment by TinyuZhao** [comment]
Fixed.
