### ISSUE TITLE
Factorytest.ino warnings and errors when trying to build in Arduino IDE

### ISSUE THREAD

**Issue by PaulskPt** [m5stack/M5Tough#4]
I encountered various errors/problems when trying to build/flash the ```..\examples\core2_for_aws\FactoryTest\FactoryTest.ino```, on a desktop PC with ```MS Windows 11 Pro``` and running ```Arduino IDE 1.8.19```.  A part of the errors have the same origin as discussed in issue #3: the lack of an IMU in the M5Stack TOUGH.

Starting with the following warning:
```In file included from C:\Users\pauls2\Documenten\Arduino\libraries\FastLED\src/FastLED.h:67,
                 from C:\Users\pauls2\Documenten\Arduino\2022-03-03_M5Stack_TOUGH_FactoryTest\2022-03-03_M5Stack_TOUGH_FactoryTest.ino:21:
C:\Users\<Username>\Documents\Arduino\libraries\FastLED\src/fastspi.h:145:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
```
I did not do anything to solve this warning.

Then Errors related to a non existant IMU: 
 ```In function 'int checkIMUInit()':
FactoryTest:448:12: error: 'class M5Tough' has no member named 'IMU'
     if (M5.IMU.Init() == 0) {
```

```C:\Users\<Username>\Documents\Arduino\libraries\M5Tough-master\examples\core2_for_aws\FactoryTest\FactoryTest.ino: In function 'void MPU6886Test()':
FactoryTest:612:8: error: 'class M5Tough' has no member named 'IMU'
     M5.IMU.getAccelData(&accX, &accY, &accZ);
        ^~~
C:\Users\<Username>\Documents\Arduino\libraries\M5Tough-master\examples\core2_for_aws\FactoryTest\FactoryTest.ino: In function 'void MPU6886Page()':
FactoryTest:1755:12: error: 'class M5Tough' has no member named 'IMU'
         M5.IMU.getAccelData(&accX, &accY, &accZ);
```
For this fact I removed: a) the checkIMUInit() function; b) the checkIMUInit() function; c) the MPU6886Page() function.

Then:
```C:\Users\<Username>\Documenten\Arduino\libraries\M5Tough-master\examples\core2_for_aws\FactoryTest\FactoryTest.ino: In function 'int checkAETCC608AInit()':
FactoryTest:473:31: error: call of overloaded 'begin(int, int, int)' is ambiguous
     Wire1.begin(21, 22, 100000);
                               ^
In file included from C:\Users\<Username>\Documenten\Arduino\libraries\ArduinoECCX08\src/ECCX08.h:24,
                 from C:\Users\<Username>\Documenten\Arduino\libraries\ArduinoECCX08\src/ArduinoECCX08.h:23,
                 from C:\Users\<Username>\Documenten\Arduino\libraries\M5Tough-master\examples\core2_for_aws\FactoryTest\FactoryTest.ino:13:
C:\Users\<Username>\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\Wire\src/Wire.h:79:10: note: candidate: 'bool TwoWire::begin(int, int, uint32_t)'
     bool begin(int sda=-1, int scl=-1, uint32_t frequency=0); // returns true, if successful init of i2c bus
          ^~~~~
C:\Users\<Username>\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.2\libraries\Wire\src/Wire.h:80:10: note: candidate: 'bool TwoWire::begin(uint8_t, int, int, uint32_t)'
     bool begin(uint8_t slaveAddr, int sda=-1, int scl=-1, uint32_t frequency=0);
```

To solve this ambiguity error:
In line 478 I changed: ```Wire1.begin(21, 22, 10000);``` into: ```Wire1.begin((uint8_t)21, 22, 10000);``` . The same in line 1947.

Then:
```../FactoryTest.ino:466:49: warning: control reaches end of non-void function [-Wreturn-type]```
```int checkAETCC608AInit()``` causes a warning because the function does not return anything.
I changed it into: ```void checkAETCC608AInit()```.

After all these corrections the sketch built and flashed to my M5Stack TOUGH, but the unit switched off immediately after only showing the text "motor test" at the bottom of the display and sounding a dualtone bleep.

A next build failed with the error that the dynaming memory was full (102%). 
```The sketch uses 1344717 bytes of the program storage. The maximum is 1310720 bytes.```
In an attempt to solve this I changed, where possible, ```Serial.print()``` commands with static texts into ```Serial.print(F("..."));``` however there were not that many of these commands. More in number were combined ```Serial.printf()``` commands.

I didn't find yet a solution to the memory full error.

**Comment by TinyuZhao** [comment]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/44396641/187185421-3ce5d5b8-7fbb-4c8f-abfe-16b0571c2d4b.png">
You can try using this partitioning scheme.

**Comment by PaulskPt** [comment]
Thank you. I go to try it in some days. I am now busy with another project.
