### ISSUE TITLE
Question: Difference to M5Unified

### ISSUE THREAD

**Issue by maxammann** [m5stack/M5Tough#7]
I'm currently building a project on the Tough. I'm unsure which library to use though to draw on the LCD and access GPIOs.

Is the M5Tough the legacy project which supports more right now but will be deprecated eventually?

Can I run M5Tough without Arduino using just esp-idf?

**Comment by TinyuZhao** [comment]
Here are some examples of LCD displays
https://github.com/m5stack/M5Tough/blob/master/examples/Basics/Display/Display.ino

**Comment by maxammann** [comment]
Thanks for the link!

The question was going into a different diction though.

Within the m5stack Github organisation there are two different projects which make it possible to draw on the Tough: M5Tough (this one) and M5Unified.
Which one should be used for new projects? Why do both exist?

**Comment by TinyuZhao** [comment]
Unified is common to many M5 devices.
Choose the one you like best, or the one you think works better.

**Comment by maxammann** [comment]
The thing is, Im not sure what would work better for me. Im looking for the more tested and more stable option.

Feature-wise both work for me.


Is there a reason why m5stack is currently maintaining libraries twice?

**Comment by TinyuZhao** [comment]
I guess you could go for M5Unified, as it is available on almost all M5 series hosts
